name: controle_de_estoque
description: Aplicativo de controle de estoque e compras para restaurante.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.3.3+1
  path: ^1.8.3
  intl: ^0.19.0
  path_provider: ^2.1.1
  logger: ^2.0.2
  collection: ^1.18.0
  dropdown_search: ^6.0.1
  provider: ^6.0.5
  flutter_local_notifications: ^17.2.3
  fl_chart: ^0.69.0
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  http: ^1.1.0
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.0.15
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env

android:
  compileSdkVersion: 33
  targetSdkVersion: 33
  minSdkVersion: 21

  # Adicione as seguintes linhas para garantir compatibilidade com Android 13+
  defaultConfig:
    multiDexEnabled: true

  # Se você estiver usando plugins que requerem permissões específicas, adicione-as aqui
  # Por exemplo:
  # uses-permission:
  #   - android.permission.INTERNET
  #   - android.permission.ACCESS_NETWORK_STATE